In [ ]:
#creating arrays
import numpy as np

a = np.array([10,20,30,40])
print(a)

b = np.arange(1,10,1)
print(b)

c = np.linspace(0,1,5)
print(c)

[10 20 30 40]
[1 2 3 4 5 6 7 8 9]
[0.   0.25 0.5  0.75 1.  ]


In [ ]:
#creating matrix
a = np.array([[1,2] ,[2,3]])
print(a)

b = np.array([[2,3],[4,5]])
print(b)

print(a+b)
print(a-b)
print(a*b)
print(a@b)

[[1 2]
 [2 3]]
[[2 3]
 [4 5]]
[[3 5]
 [6 8]]
[[-1 -1]
 [-2 -2]]
[[ 2  6]
 [ 8 15]]
[[10 13]
 [16 21]]


In [ ]:
#activity 3 = statistics
marks =np.array([70,65,80,90,88])
print(np.mean(marks))
print(np.max(marks))
print(np.min(marks))
print(np.std(marks))


78.6
90
65
9.789790600416334


In [ ]:
#take whether data of july month of udupi and find which is the hotest day and coldest day and calculate the average temperature of month find which are days above 35deg

In [ ]:

import pandas as pd

df = pd.read_csv("/udupi_july.csv")

df

,Date,Temperature
0,2025-07-01,31.2
1,2025-07-02,31.8
2,2025-07-03,30.9
3,2025-07-04,31.5
4,2025-07-05,32.0
5,2025-07-06,31.7
6,2025-07-07,30.8
7,2025-07-08,31.1
8,2025-07-09,32.3
9,2025-07-10,33.0


In [ ]:


weather_data = np.array([31.2,31.8,30.9,31.5,32.0,31.7,30.8,31.1,32.3,33.0,34.2,35.4,34.8,35.1,36.2,35.8,34.5,33.9,32.8,35.6,34.7,33.5,32.6,31.9,31.4,30.7,31.3,32.1,33.2,34.0,33.6])
print(np.max(weather_data))
print(np.mean(weather_data))
print(weather_data>29)

36.2
33.01935483870968
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True]


In [ ]:
#activit 1
import pandas as pd
student = {
    "name":["A","B","C","D"],
    "age" :[22,23,24,25],
    "marks": [90,85,75,60]
}
df = pd.DataFrame(student)
df

,name,age,marks
0,A,22,90
1,B,23,85
2,C,24,75
3,D,25,60


In [ ]:
#activity 2
from sklearn.datasets import load_iris
iris = load_iris(as_frame=True)
df = iris.frame
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0


In [ ]:
#activity 3
df.info()
df.describe()
df.column()
df.tail()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 887 entries, 0 to 886
Data columns (total 8 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   Survived                 887 non-null    int64  
 1   Pclass                   887 non-null    int64  
 2   Name                     887 non-null    object 
 3   Sex                      887 non-null    object 
 4   Age                      887 non-null    float64
 5   Siblings/Spouses Aboard  887 non-null    int64  
 6   Parents/Children Aboard  887 non-null    int64  
 7   Fare                     887 non-null    float64
dtypes: float64(2), int64(4), object(2)
memory usage: 55.6+ KB


In [ ]:
#activity 4 selecting data
#df[['sepal length (cm)','target']]
#df.iloc[:5]
#df.loc[10:20]

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
10,5.4,3.7,1.5,0.2,0
11,4.8,3.4,1.6,0.2,0
12,4.8,3.0,1.4,0.1,0
13,4.3,3.0,1.1,0.1,0
14,5.8,4.0,1.2,0.2,0
15,5.7,4.4,1.5,0.4,0
16,5.4,3.9,1.3,0.4,0
17,5.1,3.5,1.4,0.3,0
18,5.7,3.8,1.7,0.3,0
19,5.1,3.8,1.5,0.3,0


In [ ]:
#act 5 filtering data
df[df['target'] == 2]

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
100,6.3,3.3,6.0,2.5,2
101,5.8,2.7,5.1,1.9,2
102,7.1,3.0,5.9,2.1,2
103,6.3,2.9,5.6,1.8,2
104,6.5,3.0,5.8,2.2,2
105,7.6,3.0,6.6,2.1,2
106,4.9,2.5,4.5,1.7,2
107,7.3,2.9,6.3,1.8,2
108,6.7,2.5,5.8,1.8,2
109,7.2,3.6,6.1,2.5,2


In [16]:
#activity6
#df.sort_values(by='sepal length (cm)')

In [ ]:
#assignment
#use the titanic dataset csv file
#total number of passengers
#find the average age of survivers and non survivers
#list the passengers who are older than 60 years
# find the average fare for each passenger class


,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"


In [15]:
import pandas as pd


df = pd.read_csv("/train.csv")


print(df.columns)


#df.info()

# 1. Total number of passengers
total_number_of_passengers = len(df)
print("Total number of passengers:", total_number_of_passengers)

# 2. Average age of survivors and non-survivors
average_age = df.groupby("Survived")["Age"].mean()
print("Average age:")
print(average_age)

# 3. Passengers older than 60 years
older_than_60 = df[df["Age"] > 60]
print("Passengers older than 60 years:")
print(older_than_60)

# 4. Average fare for each passenger class
average_fare = df.groupby("Pclass")["Fare"].mean()
print("Average fare for each passenger class:")
print(average_fare)

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')
Total number of passengers: 891
Average age:
Survived
0    30.626179
1    28.343690
Name: Age, dtype: float64
Passengers older than 60 years:
     PassengerId  Survived  Pclass                                       Name  \
33            34         0       2                      Wheadon, Mr. Edward H   
54            55         0       1             Ostby, Mr. Engelhart Cornelius   
96            97         0       1                  Goldschmidt, Mr. George B   
116          117         0       3                       Connors, Mr. Patrick   
170          171         0       1                  Van der hoef, Mr. Wyckoff   
252          253         0       1                  Stead, Mr. William Thomas   
275          276         1       1          Andrews, Miss. Kornelia Theodosia   
280          281         0       3                       